# Heuristic Identification of Biological Architectures for simulating Complex Hierarchical Interactions (HIBACHI)
---
## Modifying Traditional Polygenic Risk Scores

Existing polygenic risk scores represent the weighted sum of all risk alleles carried by an individual. 
$$PRS=\sum_{i=1}^{29} \beta_i \cdot SNP_i$$


$$GRS=\sum_{i=1}^{29} FS_i \cdot \beta_i \cdot SNP_i$$

In [1]:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import eli5
from eli5.sklearn import PermutationImportance

bcdata = pd.read_csv('breastCancer29.csv')

Xdata = bcdata.loc[:, bcdata.columns != 'phenotype']
Ydata = bcdata['phenotype']
X_train, X_test, Y_train, Y_test = train_test_split(Xdata, Ydata, random_state=42,
                                                    train_size=0.75, test_size=0.25)

model = TPOTClassifier(generations=100, population_size=100, verbosity=2, max_time_mins=5, early_stop=5)
model = model.fit(X_train, Y_train)

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.

HBox(children=(IntProgress(value=0, description='Optimization Progress', style=ProgressStyle(description_widthâ€¦

Generation 1 - Current best internal CV score: 0.5639008860545177

5.266051533333334 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: LinearSVC(input_matrix, C=20.0, dual=True, loss=hinge, penalty=l2, tol=0.01)

In [15]:
bcdata.head(10)

,rs616488,rs11249433,rs4849887,rs2016394,rs1550623,rs6762644,rs4973768,rs1053338,rs1353747,rs1432679,...,rs3817198,rs17356907,rs1292011,rs999737,rs11627032,rs13329835,rs1436904,rs3760982,rs2823093,phenotype
0,1,0,0,1,0,1,2,0,0,0,...,1,0,1,1,0,1,1,1,1,0
1,1,1,0,0,0,1,2,0,0,1,...,0,1,1,2,2,0,1,1,0,1
2,1,1,0,0,0,0,1,0,0,0,...,0,0,1,0,0,1,0,1,1,1
3,0,1,0,1,1,0,0,0,0,1,...,1,2,2,1,0,0,0,2,1,0
4,1,0,0,0,1,1,2,0,0,2,...,1,1,1,0,0,1,1,2,0,1
5,0,0,1,1,1,2,2,0,1,2,...,1,1,1,0,0,0,0,1,1,0
6,1,0,0,1,0,1,2,0,0,1,...,0,0,1,1,0,1,0,0,1,0
7,0,1,0,1,0,0,0,1,0,2,...,0,0,0,0,1,2,1,1,0,1
8,1,1,0,0,0,1,2,0,0,2,...,1,0,0,1,1,1,2,1,1,1
9,0,1,1,2,0,2,2,0,0,1,...,0,0,1,0,0,0,0,2,1,1

In [2]:

perm = PermutationImportance(model, n_iter=100).fit(X_train, Y_train)
feat_imp = perm.feature_importances_
feat_name = X_train.columns.values
importance_df = pd.DataFrame({'feat': feat_name, 'score': feat_imp})
importance_df.sort_values('score', ascending = False)

          feat  score
0     rs616488    0.0
15   rs1011970    0.0
27   rs3760982    0.0
26   rs1436904    0.0
25  rs13329835    0.0
24  rs11627032    0.0
23    rs999737    0.0
22   rs1292011    0.0
21  rs17356907    0.0
20   rs3817198    0.0
19  rs11199914    0.0
18   rs7904519    0.0
17    rs704010    0.0
16   rs7072776    0.0
14  rs11780156    0.0
1   rs11249433    0.0
13   rs9693444    0.0
12    rs720475    0.0
11  rs11977670    0.0
10    rs204247    0.0
9    rs1432679    0.0
8    rs1353747    0.0
7    rs1053338    0.0
6    rs4973768    0.0
5    rs6762644    0.0
4    rs1550623    0.0
3    rs2016394    0.0
2    rs4849887    0.0
28   rs2823093    0.0

In [48]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
LogisticRegression(solver='lbfgs')


import plotly.figure_factory as ff
import pandas as pd
import numpy as np
import io
import requests

url = "https://raw.githubusercontent.com/Hoytgong/vgmed/master/finalBCdata.csv"
s = requests.get(url).content
df = pd.read_csv(io.StringIO(s.decode('utf-8')))
df_id = df.drop('phenotype', axis=1)
features = df_id.drop('patient_id', axis=1).values

training_features, testing_features, training_target, testing_target = \
            train_test_split(features, df['phenotype'].values, random_state=42)

x_row = df_id.loc[df_id.patient_id == int('1221'), :]
x_features = x_row.drop('patient_id', axis=1).values
original_prob = exported_pipeline.predict_proba(x_features)[:, 1][0]

NameError: name 'exported_pipeline' is not defined

In [18]:
x_row

,patient_id,rs616488,rs11249433,rs4849887,rs2016394,rs1550623,rs6762644,rs4973768,rs1053338,rs1353747,...,rs11199914,rs3817198,rs17356907,rs1292011,rs999737,rs11627032,rs13329835,rs1436904,rs3760982,rs2823093
396,1221,0.0,0.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0

In [17]:
x_features

array([[0., 0., 2., 2., 0., 2., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
        1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1.]])

In [47]:
# Coefficients from logit regression forms Betas for PRS function

from sklearn.linear_model import LogisticRegression
LogisticRegression(solver='lbfgs')
import warnings
warnings.filterwarnings("ignore")

# initialize list of betas to be a matrix. Each is the coefficient of the logit model, on each SNP/feature
listofbetas = []
for i in range(X_train.shape[1]):
    logit = LogisticRegression()
    logit.fit(X_train, Y_train)
    beta = logit.coef_.flatten()[i]
    listofbetas.append(beta)
    
beta_matrix = np.matrix(listofbetas).transpose()
y_matrix = np.matrix(X_test)
# beta_matrix.shape == (29,1)
# y_matrix.shape == (626, 29)
PRS = y_matrix * beta_matrix

print(beta_matrix.shape)
print(x_features.shape)
beta_prob_val = x_features * beta_matrix # np.array(beta_prob_val)[0][0]
beta_prob_val

(29, 1)
(1, 29)

matrix([[-0.19411417]])

In [4]:
scalar = np.matrix(feat_imp).flatten().transpose()
beta_FS = np.multiply(scalar, beta_matrix)
GRS = y_matrix * beta_FS

In [5]:
print(PRS.shape)
print(GRS.shape)

(626, 1)
(626, 1)

In [7]:
PRS_df = pd.DataFrame(PRS, columns=['PRS_score'])
GRS_df = pd.DataFrame(GRS, columns=['GRS_score'])
phenotypes = pd.DataFrame(Y_test).reset_index().rename(columns={'index':'subject_id'})
sub_ids = pd.DataFrame(X_test.index.values, columns=["subject_id"])

In [8]:
print(PRS_df.shape)
print(GRS_df.shape)
print(phenotypes.shape)
print(sub_ids.shape)

(626, 1)
(626, 1)
(626, 2)
(626, 1)

In [14]:
final_df = pd.concat([sub_ids, PRS_df, GRS_df], axis=1)
final_df = final_df.merge(phenotypes, on="subject_id")
final_df.head(50)

    subject_id  PRS_score  GRS_score  phenotype
0         1835   0.038244        0.0          1
1          252   0.117780        0.0          1
2         1594   0.109034        0.0          0
3          430   0.075651        0.0          0
4         1356   0.020889        0.0          1
5         1620  -0.702346        0.0          0
6         2196   0.238912        0.0          1
7         1070  -0.696288        0.0          0
8          239   0.001112        0.0          0
9         1486   0.340831        0.0          0
10        2221   0.064544        0.0          0
11         354  -0.003011        0.0          1
12         445   0.103236        0.0          0
13        2031  -0.187861        0.0          0
14          93  -0.725919        0.0          0
15        2136   0.347166        0.0          0
16        1368  -0.188454        0.0          0
17        2413   0.067341        0.0          0
18        1241  -0.141234        0.0          1
19         782  -0.102935        0.0          1
20        2455   0.107334        0.0          0
21         940   0.189483        0.0          0
22        2104  -0.334291        0.0          1
23        1674  -0.126708        0.0          1
24          56   0.042467        0.0          1
25         495   0.064950        0.0          0
26        2365  -0.257593        0.0          0
27        2276   0.395633        0.0          0
28         670  -0.202420        0.0          1
29        2311   0.067581        0.0          0
30         859  -0.122746        0.0          1
31        1580   0.018298        0.0          1
32        2330   0.212700        0.0          0
33        1968   0.531862        0.0          0
34         402   0.100177        0.0          0
35        1880  -0.259802        0.0          0
36        2036   0.287633        0.0          1
37        1389   0.031208        0.0          0
38         518   0.252329        0.0          1
39        1073   0.806222        0.0          0
40        1001  -0.043314        0.0          1
41        1185   0.235066        0.0          0
42         929   0.027707        0.0          1
43        2025  -0.357975        0.0          0
44        2184  -0.114745        0.0          0
45         869   0.248094        0.0          0
46        1935   0.057510        0.0          1
47         755   0.561341        0.0          1
48        1599  -0.191564        0.0          0
49         662  -0.002343        0.0          0

In [12]:
final_df.to_csv('PRS_GRS_scores.csv', index=False)

In [1]:
os.getcwd()

NameError: name 'os' is not defined

In [2]:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [ ]:
import os
import glob 

path = '/Users/hoytgong/Documents/MooreLab/'
extension = 'csv'
os.chdir(path + "csv_data_300/")
data_sets = [i.replace(".csv", "") for i in glob.glob('*.{}'.format(extension))]
os.chdir(path)

for dat_name in data_sets:
    accuracy_ls = []
    tpot_data = pd.read_csv(path + "csv_data_300/" + dat_name + '.csv')
    Xdata = tpot_data.loc[:, tpot_data.columns != 'Class']
    Ydata = tpot_data['Class']
    X_train, X_test, y_train, y_test = train_test_split(Xdata, Ydata,
                                                        train_size=0.75, test_size=0.25)

    tpot = TPOTClassifier(generations=100,
                          population_size=100, verbosity=2)

    tpot.fit(X_train, y_train)
    accuracy_ls.append([tpot._optimized_pipeline_score, tpot.score(X_test, y_test)])
    tpot.export('pipelines/' + dat_name + '.py')

    accuracy_mat = pd.DataFrame(accuracy_ls, columns = ['Training CV Accuracy', 'Testing Accuracy'])
    accuracy_mat.to_csv("accuracies/" + dat_name + ".csv", sep = "\t")

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.

HBox(children=(IntProgress(value=0, description='Optimization Progress', max=10100, style=ProgressStyle(descriâ€¦

Generation 1 - Current best internal CV score: 0.9959910514541386
Generation 2 - Current best internal CV score: 0.9959910514541386
Generation 3 - Current best internal CV score: 0.9959910514541386
Generation 4 - Current best internal CV score: 0.9959910514541386
Generation 5 - Current best internal CV score: 0.9959910514541386
Generation 6 - Current best internal CV score: 0.9959910514541386
Generation 7 - Current best internal CV score: 0.9959910514541386
Generation 8 - Current best internal CV score: 0.9959910514541386
Generation 9 - Current best internal CV score: 0.9959910514541386
Generation 10 - Current best internal CV score: 0.9959910514541386
Generation 11 - Current best internal CV score: 0.9959910514541386
Generation 12 - Current best internal CV score: 0.9959910514541386
Generation 13 - Current best internal CV score: 0.9959910514541386
Generation 14 - Current best internal CV score: 0.9959910514541386